-- ===========================================================================
-- FROZEN. This file is no longer the place to change the schema.
--
-- It is kept because it is readable start to finish — the security model, the
-- reasoning behind every policy, and the two or three traps that cost real data
-- to learn — and that is worth having in one document. As a description of what
-- the databases contain it is accurate as of the baseline migration.
--
-- But it is no longer authoritative, because it cannot express "what changed".
-- The migration history is:
--
--   supabase/migrations/20260811000000_baseline_schema.sql   <- a copy of this
--   supabase/migrations/<timestamp>_<name>.sql               <- everything after
--
-- To change the schema, add a new migration. Do not edit this file and do not
-- edit the baseline: a change made here reaches neither database, and worse, it
-- makes this file disagree with them. See DATABASE.md for the workflow.
-- ===========================================================================

-- 1Elevate — database schema for Supabase (Postgres).
--
-- Run this once in the Supabase SQL Editor. It is written to be re-runnable:
-- every statement is guarded, so running it twice changes nothing.
--
-- The security model in one sentence: a student can only ever touch their own
-- rows, an admin can read everything, and the question bank is readable by any
-- signed-in student but writable only by an admin.
--
-- Row-level security is what enforces that, and it is enabled on every table
-- below. Without it, any key that reaches a browser can read the whole table.
--
-- ── On the order of this file ──────────────────────────────────────────────
-- Postgres resolves what a statement names at the moment it runs, so the order
-- here is load-bearing, not stylistic:
--
--   1. the profiles table       — is_admin() reads from it
--   2. is_admin()               — every policy below calls it
--   3. policies, other tables, and the signup trigger
--
-- Declaring the helper at the bottom, where it reads more naturally, fails with
-- "function public.is_admin() does not exist" on the first policy.
--
-- ── RLS is not the whole story ─────────────────────────────────────────────
-- A policy decides which ROWS a statement may touch. It cannot decide which
-- COLUMNS. Anything that must not be self-assigned — `role`, above all — needs
-- a column-level GRANT as well, and there is one further down. Policies alone
-- let a student send one PATCH to the REST API and make themselves an admin.

-- ---------------------------------------------------------------- profiles --
-- One row per signed-in student. `id` is the same id Supabase Auth issues, so
-- the profile and the login are the same person by construction; there are no
-- passwords here, because Supabase Auth owns them.

create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  name         text not null default '',
  email        text not null default '',
  grade        text not null default '',
  -- student — practises.
  -- admin   — everything a student can do, plus writes the shared question bank.
  -- owner   — everything an admin can do, plus appoints and removes admins.
  role         text not null default 'student' check (role in ('student', 'admin', 'owner')),
  target_score int  not null default 1400 check (target_score between 400 and 1600),
  created_at   timestamptz not null default now()
);

-- `create table if not exists` does nothing at all on a table that already
-- exists, including to its constraints. A database created before the owner
-- role still carries check (role in ('student','admin')), and would reject
-- 'owner' with a constraint violation. Replacing it explicitly is what makes
-- this file work on an existing project as well as a fresh one.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check check (role in ('student', 'admin', 'owner'));

-- ------------------------------------------------------------------ helper --
-- Defined here, before the first policy that calls it.
--
-- SECURITY DEFINER is a necessity, not a convenience: a policy on profiles that
-- asked "is this user an admin?" by selecting from profiles would re-enter that
-- same policy and recurse forever. A definer function runs as its owner, skips
-- RLS, and breaks the cycle.
--
-- `search_path` is pinned because a definer function that resolves names
-- through the caller's path can be pointed at tables the caller controls.

-- True for admins AND owners. An owner is an admin with extra powers, so every
-- content policy below is written once against this and never has to remember
-- to mention 'owner' as well — forgetting that in one policy is exactly how an
-- owner ends up unable to edit the bank they administer.
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'owner')
  );
$$;

-- The narrower check: appointing and removing admins.
create or replace function public.is_owner()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'owner'
  );
$$;

-- The only way `role` can change from a browser.
--
-- The column grant further down deliberately leaves `role` unwritable, so no
-- UPDATE from a signed-in user can touch it. This function is SECURITY DEFINER,
-- meaning it runs as its owner and is not bound by that grant — which is the
-- point. It is a single, audited doorway rather than a permission.
--
-- The guards, in order, and why each exists:
--   * only an owner may call it at all;
--   * only 'student' and 'admin' can be assigned, so nobody can mint an owner
--     through the UI;
--   * you cannot change your own role, so the last owner cannot accidentally
--     demote themselves and lock the project out of its own admin controls;
--   * an existing owner cannot be demoted here, so two owners cannot strip each
--     other in a race. Owners are made and unmade in the SQL editor only.
create or replace function public.set_role(target_id uuid, new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_owner() then
    raise exception 'Only the owner can change roles' using errcode = '42501';
  end if;

  if new_role not in ('student', 'admin') then
    raise exception 'Role must be student or admin' using errcode = '22023';
  end if;

  if target_id = auth.uid() then
    raise exception 'You cannot change your own role' using errcode = '42501';
  end if;

  if exists (select 1 from public.profiles where id = target_id and role = 'owner') then
    raise exception 'An owner can only be changed in the SQL editor' using errcode = '42501';
  end if;

  update public.profiles set role = new_role where id = target_id;
end;
$$;

-- Signed-in callers only. anon has no business reaching this at all.
revoke execute on function public.set_role(uuid, text) from anon, public;
grant execute on function public.set_role(uuid, text) to authenticated;

-- --------------------------------------------------------- profile access --

alter table public.profiles enable row level security;

drop policy if exists "profiles: read own or admin" on public.profiles;
create policy "profiles: read own or admin"
  on public.profiles for select
  using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles: update own" on public.profiles;
create policy "profiles: update own"
  on public.profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

-- Deliberately no INSERT policy: profiles are created by the trigger at the
-- bottom, and no DELETE policy, because closing an account is not self-service.

-- The policy above says WHICH ROW a student may update — their own. It says
-- nothing about which columns, and on its own that is a privilege escalation:
--
--   PATCH /rest/v1/profiles?id=eq.<self>  {"role":"admin"}
--
-- succeeds, because the row is theirs. The API route drops `role` from its
-- payload, but the route is not the only way in — the publishable key ships in
-- every browser and PostgREST is reachable directly.
--
-- Column-level privileges are the fix, and they are checked independently of
-- RLS: revoke UPDATE wholesale, then grant it back only on the three columns a
-- student is allowed to edit. `role` is not among them, so the PATCH above now
-- fails with "permission denied for table profiles" no matter which row it
-- targets. INSERT and DELETE go too; the trigger below is SECURITY DEFINER and
-- is unaffected, as is anything using the service key.
--
-- SELECT is deliberately left alone — reading is already governed by the read
-- policy above.

revoke insert, update, delete on public.profiles from anon, authenticated;
grant update (name, grade, target_score) on public.profiles to authenticated;

-- ---------------------------------------------------------------- attempts --
-- Append-only log of answered questions. Everything on the progress page is
-- derived from this table.

create table if not exists public.attempts (
  id          bigserial primary key,
  account_id  uuid not null references public.profiles (id) on delete cascade,
  question_id text not null,
  subject_id  text not null,
  exam        text not null,
  topic       text not null,
  difficulty  int,
  chosen      int  not null,
  correct     boolean not null,
  mode        text not null check (mode in ('practice', 'mock', 'review')),
  ms          int  not null default 0,
  at          timestamptz not null default now()
);

-- Every analytics query filters by student, newest first.
create index if not exists attempts_by_account on public.attempts (account_id, at desc);

-- An attempt carries no client-side id, so the sync layer identifies one by
-- who answered, which question, when, and in which mode. The unique index below
-- makes that identity real, which is what lets the API insert with ON CONFLICT
-- DO NOTHING: a retry after a dropped connection becomes a no-op instead of a
-- second copy of the same answer.
--
-- The delete runs first because CREATE UNIQUE INDEX fails outright if the table
-- already holds duplicates — which it will, on any database that synced before
-- this index existed. It keeps the lowest id of each group and removes the rest,
-- so it only ever deletes rows that are byte-for-byte repeats of a row it keeps.
-- On a clean table it matches nothing, which keeps this file re-runnable.
--
-- The same question cannot genuinely be answered twice in one millisecond in
-- one mode, so this never rejects a real attempt.

delete from public.attempts a
using public.attempts b
where a.id > b.id
  and a.account_id  = b.account_id
  and a.question_id = b.question_id
  and a.at          = b.at
  and a.mode        = b.mode;

create unique index if not exists attempts_unique_answer
  on public.attempts (account_id, question_id, at, mode);

alter table public.attempts enable row level security;

drop policy if exists "attempts: read own or admin" on public.attempts;
create policy "attempts: read own or admin"
  on public.attempts for select
  using (account_id = auth.uid() or public.is_admin());

-- `with check` and not `using`: this is the rule for rows being written, and it
-- is what stops a student posting an attempt under someone else's id.
drop policy if exists "attempts: insert own" on public.attempts;
create policy "attempts: insert own"
  on public.attempts for insert
  with check (account_id = auth.uid());

-- No update or delete policy: the log is append-only, so a student cannot
-- rewrite history to improve their own analytics.

-- ------------------------------------------------------------------- mocks --

create table if not exists public.mocks (
  id         text primary key,
  account_id uuid not null references public.profiles (id) on delete cascade,
  exam       text not null,
  score      int  not null,
  correct    int  not null,
  total      int  not null,
  sections   jsonb not null default '[]'::jsonb,
  wrong      jsonb not null default '[]'::jsonb,
  at         timestamptz not null default now()
);

create index if not exists mocks_by_account on public.mocks (account_id, at desc);

alter table public.mocks enable row level security;

drop policy if exists "mocks: read own or admin" on public.mocks;
create policy "mocks: read own or admin"
  on public.mocks for select
  using (account_id = auth.uid() or public.is_admin());

-- Insert only, and no update policy on purpose: a finished exam is a fact, not
-- a draft. The API relies on this — it writes with ON CONFLICT DO NOTHING, so a
-- re-sent mock is ignored rather than taking an UPDATE path that RLS refuses.
drop policy if exists "mocks: insert own" on public.mocks;
create policy "mocks: insert own"
  on public.mocks for insert
  with check (account_id = auth.uid());

-- -------------------------------------------------------- custom questions --
-- The shared bank written in the admin editor. Every student reads it; only an
-- admin writes it.

create table if not exists public.custom_questions (
  id         text primary key,
  exam       text not null,
  subject_id text not null,
  topic      text not null,
  domain     text,
  difficulty int  not null check (difficulty between 1 and 3),
  payload    jsonb not null,
  answer     int  not null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.custom_questions enable row level security;

drop policy if exists "questions: read signed in" on public.custom_questions;
create policy "questions: read signed in"
  on public.custom_questions for select
  to authenticated
  using (true);

drop policy if exists "questions: write admin" on public.custom_questions;
create policy "questions: write admin"
  on public.custom_questions for all
  using (public.is_admin())
  with check (public.is_admin());

-- --------------------------------------------------------- signup trigger --
-- A profile for every new signup, filled from whatever the sign-up form passed
-- as metadata. Without this a student authenticates successfully and then has
-- nowhere to store a target score.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ------------------------------------------------------- making the owner --
-- Exactly one step is manual, and deliberately so: there is no way to become
-- the owner through the app, because the first owner is the thing every other
-- permission is derived from.
--
-- Sign up through the app normally, then run this once with your own address:
--
--   update public.profiles set role = 'owner' where email = 'you@example.com';
--
-- From then on everything else is done in the app: Admin → People lets you
-- appoint admins, who can write the shared question bank, and demote them
-- again. set_role() refuses to mint another owner, so a second owner is also a
-- SQL-editor job — worth doing for one trusted person, so a lost account does
-- not leave the project with nobody able to appoint anyone.
--
-- To audit who holds what, especially on a database that ran the version of
-- this file where a student could grant themselves admin:
--
--   select email, role from public.profiles where role <> 'student';

-- =========================================================== community ==
-- The feed: posts, reactions, comments and saves.
--
-- Everything a student writes is attributed to their auth id, never to a name
-- sent by the browser, so a post cannot be published under someone else's
-- identity no matter what the client sends.

-- ------------------------------------------------------- public profiles --
-- Names have to be visible to everyone or a feed is anonymous, but the
-- profiles table also holds email, grade and target score, and its read policy
-- correctly limits a student to their own row.
--
-- This view is the narrow window through it: id and display name, nothing else.
-- It is deliberately NOT security_invoker, so it runs as its owner and is not
-- blocked by that policy — which is safe precisely because the column list is
-- fixed here and cannot be widened by a caller.

create or replace view public.public_profiles as
  select
    id,
    -- Never expose the address. A student who set no name is shown the part
    -- before the @, which is what they would have been called anyway.
    coalesce(nullif(trim(name), ''), split_part(coalesce(email, ''), '@', 1), 'Student') as display_name,
    role
  from public.profiles;

revoke all on public.public_profiles from anon, public;
grant select on public.public_profiles to authenticated;

-- -------------------------------------------------------------- posts --

create table if not exists public.community_posts (
  id         uuid primary key default gen_random_uuid(),
  author_id  uuid not null references public.profiles (id) on delete cascade,
  -- 'post' is an ordinary user-authored post: words, and nothing structured.
  -- The other six are shapes the product understands — a question carries an
  -- answer pair, progress carries two scores — and five of them are on their way
  -- to being written by the app itself rather than by a person choosing a
  -- category from a list.
  type       text not null check (type in
               ('post', 'question', 'progress', 'achievement', 'explanation',
                'study-update', 'resource')),
  exam       text not null default 'sat',
  topic      text,
  text       text,
  -- The type-specific block, kept as jsonb for the same reason the question
  -- bank does: six post shapes would otherwise mean six sets of nullable
  -- columns, and a new post type would mean a migration.
  payload    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- `create table if not exists` leaves an existing table's constraints alone, so
-- a project created before 'post' was a type still carries the six-value check
-- and would reject an ordinary post with a constraint violation. Replacing it
-- explicitly is what lets this file run against an existing project as well as
-- a fresh one — the same reason profiles_role_check is replaced above.
alter table public.community_posts drop constraint if exists community_posts_type_check;
alter table public.community_posts
  add constraint community_posts_type_check check (type in
    ('post', 'question', 'progress', 'achievement', 'explanation',
     'study-update', 'resource'));

create index if not exists community_posts_recent on public.community_posts (created_at desc);

-- Moderation, kept reversible. A hidden post is still a row: it leaves every
-- student's feed immediately, and an admin who hid the wrong thing can put it
-- back. Hard deletion stays the author's own choice, which is the one case where
-- the person asking is entitled to lose the data.
alter table public.community_posts
  add column if not exists hidden_at timestamptz,
  add column if not exists hidden_by uuid references public.profiles (id) on delete set null;

alter table public.community_posts enable row level security;

-- Hidden means hidden, in the database and not merely in the query the feed
-- happens to send. An admin still reads it, because the moderation queue has to
-- show what it is moderating.
drop policy if exists "posts: read signed in" on public.community_posts;
create policy "posts: read signed in"
  on public.community_posts for select to authenticated
  using (hidden_at is null or public.is_admin());

drop policy if exists "posts: insert own" on public.community_posts;
create policy "posts: insert own"
  on public.community_posts for insert
  with check (author_id = auth.uid());

drop policy if exists "posts: update own" on public.community_posts;
create policy "posts: update own"
  on public.community_posts for update
  using (author_id = auth.uid()) with check (author_id = auth.uid());

-- Authors can withdraw their own post; admins can remove anyone's, because a
-- feed with no moderation is a liability the moment it has real users.
drop policy if exists "posts: delete own or admin" on public.community_posts;
create policy "posts: delete own or admin"
  on public.community_posts for delete
  using (author_id = auth.uid() or public.is_admin());

-- The same trap the profiles table fell into, for the same reason: the update
-- policy above says WHICH ROW an author may write — their own — and says nothing
-- about which columns. `hidden_at` lives in that row, so under policies alone an
-- author whose post an admin had hidden could send
--
--   PATCH /rest/v1/community_posts?id=eq.<their own post>  {"hidden_at":null}
--
-- straight to PostgREST with the publishable key and put it back. That is a
-- moderation bypass, not a cosmetic problem.
--
-- Column privileges are checked independently of RLS, so revoking UPDATE and
-- granting it back on only the three columns a post's own words live in closes
-- it: hidden_at and hidden_by are not writable by anyone signed in, and the only
-- thing that sets them is the definer function below, which checks is_admin()
-- first. author_id is left out too, so a post cannot be reassigned.
revoke update on public.community_posts from anon, authenticated;
grant update (text, topic, payload) on public.community_posts to authenticated;

-- ---------------------------------------------------------- reactions --
-- The composite primary key is what makes a reaction idempotent: reacting
-- twice is the same row, so a double tap or a retry cannot inflate a count.

create table if not exists public.community_reactions (
  post_id    uuid not null references public.community_posts (id) on delete cascade,
  account_id uuid not null references public.profiles (id) on delete cascade,
  kind       text not null check (kind in ('helpful', 'congrats')),
  created_at timestamptz not null default now(),
  primary key (post_id, account_id, kind)
);

alter table public.community_reactions enable row level security;

drop policy if exists "reactions: read signed in" on public.community_reactions;
create policy "reactions: read signed in"
  on public.community_reactions for select to authenticated using (true);

drop policy if exists "reactions: write own" on public.community_reactions;
create policy "reactions: write own"
  on public.community_reactions for insert
  with check (account_id = auth.uid());

drop policy if exists "reactions: remove own" on public.community_reactions;
create policy "reactions: remove own"
  on public.community_reactions for delete
  using (account_id = auth.uid());

-- ----------------------------------------------------------- comments --

create table if not exists public.community_comments (
  id         uuid primary key default gen_random_uuid(),
  post_id    uuid not null references public.community_posts (id) on delete cascade,
  author_id  uuid not null references public.profiles (id) on delete cascade,
  text       text not null check (length(trim(text)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists community_comments_by_post
  on public.community_comments (post_id, created_at);

-- Hidden the same way a post is, and for the same reason: an abusive reply needs
-- removing from every screen without destroying the record of what was said.
alter table public.community_comments
  add column if not exists hidden_at timestamptz,
  add column if not exists hidden_by uuid references public.profiles (id) on delete set null;

alter table public.community_comments enable row level security;

drop policy if exists "comments: read signed in" on public.community_comments;
create policy "comments: read signed in"
  on public.community_comments for select to authenticated
  using (hidden_at is null or public.is_admin());

drop policy if exists "comments: insert own" on public.community_comments;
create policy "comments: insert own"
  on public.community_comments for insert
  with check (author_id = auth.uid());

drop policy if exists "comments: delete own or admin" on public.community_comments;
create policy "comments: delete own or admin"
  on public.community_comments for delete
  using (author_id = auth.uid() or public.is_admin());

-- There is deliberately no update policy, so RLS already refuses every UPDATE:
-- a comment cannot be edited, and hidden_at therefore cannot be cleared by the
-- person who wrote it. The revoke says the same thing a second way, so that
-- adding an "edit your reply" policy later cannot silently hand over the
-- moderation column with it.
revoke update on public.community_comments from anon, authenticated;

-- -------------------------------------------------------------- saves --
-- A private bookmark. Unlike a reaction, nobody else may read it, so the read
-- policy is the student's own rows only.

create table if not exists public.community_saves (
  post_id    uuid not null references public.community_posts (id) on delete cascade,
  account_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, account_id)
);

alter table public.community_saves enable row level security;

drop policy if exists "saves: read own" on public.community_saves;
create policy "saves: read own"
  on public.community_saves for select using (account_id = auth.uid());

drop policy if exists "saves: write own" on public.community_saves;
create policy "saves: write own"
  on public.community_saves for insert
  with check (account_id = auth.uid());

drop policy if exists "saves: remove own" on public.community_saves;
create policy "saves: remove own"
  on public.community_saves for delete
  using (account_id = auth.uid());

-- ------------------------------------------------------------- reports --
-- What one student says about another's post or reply.
--
-- Separate from `feedback`, which is a message to the team about the product.
-- A report is about a specific piece of content, it needs a decision, and the
-- two lists are read by an admin for entirely different reasons. Sharing one
-- table would mean a nullable target on every product suggestion.
--
-- The target is a (type, id) pair rather than two nullable foreign keys, because
-- a report points at exactly one thing and a pair of columns where one is always
-- null invites the row that sets both. The cost is no referential integrity on
-- target_id, which is why the API reads the target back and the queue skips a
-- report whose content has since been deleted outright.

create table if not exists public.community_reports (
  id          uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id   uuid not null,
  -- Five reasons, not twenty. A longer list makes the reporter classify rather
  -- than report, and every extra category is one an admin has to weigh.
  reason      text not null check (reason in
                ('harassment', 'spam', 'inappropriate', 'misinformation', 'other')),
  -- Optional. The sentence that explains what the category cannot.
  details     text check (details is null or char_length(btrim(details)) <= 1000),
  status      text not null default 'open'
              check (status in ('open', 'dismissed', 'actioned')),
  created_at  timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles (id) on delete set null
);

-- One report per person per target. This is the whole duplicate defence, and it
-- is here rather than in the API because a loop calling the endpoint a thousand
-- times has to hit something that cannot be raced. A second report of the same
-- thing by the same person is a no-op the API reports as already-reported; a
-- second report by a DIFFERENT person is a separate row on purpose, because how
-- many people reported something is the most useful signal in the queue.
create unique index if not exists community_reports_one_per_reporter
  on public.community_reports (reporter_id, target_type, target_id);

-- The queue reads open reports newest first.
create index if not exists community_reports_open
  on public.community_reports (status, created_at desc);

alter table public.community_reports enable row level security;

-- A reporter may read their own reports back, so the UI can say "you reported
-- this" instead of failing on the unique index. Nobody else's are visible to
-- them: who reported what is between the reporter and the team, and a feed where
-- the author can see who reported them is a feed that punishes reporting.
drop policy if exists "reports: read own or admin" on public.community_reports;
create policy "reports: read own or admin"
  on public.community_reports for select
  using (reporter_id = auth.uid() or public.is_admin());

-- `with check`, so the reporter id is the caller's own and cannot be forged into
-- someone else's name.
drop policy if exists "reports: insert own" on public.community_reports;
create policy "reports: insert own"
  on public.community_reports for insert
  with check (reporter_id = auth.uid());

-- Only an admin resolves one, and only through the functions below. No update
-- policy for the reporter: withdrawing a report is not a feature, and letting
-- the reporter rewrite `reason` after an admin has read it makes the queue a
-- record of nothing.
drop policy if exists "reports: update admin" on public.community_reports;
create policy "reports: update admin"
  on public.community_reports for update
  using (public.is_admin())
  with check (public.is_admin());

-- No delete policy at all: a resolved report is the audit trail.

-- --------------------------------------------------- moderation actions --
-- Hiding a piece of content and settling its reports are one decision, so they
-- are one statement. Doing it from the client as two calls leaves a queue full
-- of open reports pointing at content that is already gone the moment the second
-- call fails.
--
-- SECURITY DEFINER for the same reason set_role() is: the column grant above
-- makes hidden_at unwritable by anyone signed in, and this function — running as
-- its owner — is the single audited doorway that may set it. The is_admin()
-- check on the first line is the real permission.

create or replace function public.moderate_hide(
  p_target_type text,
  p_target_id   uuid,
  p_hidden      boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only an admin can moderate' using errcode = '42501';
  end if;

  if p_target_type not in ('post', 'comment') then
    raise exception 'Target must be a post or a comment' using errcode = '22023';
  end if;

  if p_target_type = 'post' then
    update public.community_posts
       set hidden_at = case when p_hidden then now() else null end,
           hidden_by = case when p_hidden then auth.uid() else null end
     where id = p_target_id;
  else
    update public.community_comments
       set hidden_at = case when p_hidden then now() else null end,
           hidden_by = case when p_hidden then auth.uid() else null end
     where id = p_target_id;
  end if;

  if not found then
    raise exception 'That content no longer exists' using errcode = 'P0002';
  end if;

  -- Hiding settles the reports that asked for it. Un-hiding deliberately does
  -- not reopen them: the admin has now looked twice, and a report that keeps
  -- coming back is a queue nobody can empty.
  update public.community_reports
     set status      = case when p_hidden then 'actioned' else 'dismissed' end,
         reviewed_at = now(),
         reviewed_by = auth.uid()
   where target_type = p_target_type
     and target_id   = p_target_id
     and status      = 'open';
end;
$$;

-- The other verdict: nothing wrong with it. Leaves the content exactly as it is
-- and takes its reports out of the queue.
create or replace function public.moderate_dismiss(
  p_target_type text,
  p_target_id   uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only an admin can moderate' using errcode = '42501';
  end if;

  update public.community_reports
     set status      = 'dismissed',
         reviewed_at = now(),
         reviewed_by = auth.uid()
   where target_type = p_target_type
     and target_id   = p_target_id
     and status      = 'open';
end;
$$;

revoke execute on function public.moderate_hide(text, uuid, boolean) from anon, public;
grant execute on function public.moderate_hide(text, uuid, boolean) to authenticated;
revoke execute on function public.moderate_dismiss(text, uuid) from anon, public;
grant execute on function public.moderate_dismiss(text, uuid) to authenticated;

-- ---------------------------------------------------------------- feedback --
-- What students tell the team. Insert-your-own, read-by-admins: a student can
-- send a message and can read their own back, and nobody but an admin or the
-- owner can read anyone else's — feedback is often about a person's own
-- difficulty with the product, and it is written on the understanding that the
-- team reads it, not the class.

create table if not exists public.feedback (
  id         uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.profiles (id) on delete cascade,
  -- Free text. Kept as one column rather than a form: the useful part of
  -- feedback is the sentence nobody anticipated a field for.
  message    text not null check (char_length(btrim(message)) between 1 and 4000),
  -- What the student says it is about, from a fixed list the app offers.
  category   text not null default 'other'
             check (category in ('bug', 'content', 'idea', 'other')),
  -- Set by an admin once it has been dealt with, so a long list stays workable.
  handled_at timestamptz,
  -- Screenshots, as object paths in the feedback-shots bucket below. A bug
  -- report is usually a description of something on screen, and the screen
  -- itself says it in one go: the paths live here, the bytes live in storage.
  shots      text[] not null default '{}'
             check (array_length(shots, 1) is null or array_length(shots, 1) <= 3),
  created_at timestamptz not null default now()
);

-- Existing installs predate the column.
alter table public.feedback
  add column if not exists shots text[] not null default '{}';

create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);

alter table public.feedback enable row level security;

drop policy if exists "feedback: read own or admin" on public.feedback;
create policy "feedback: read own or admin"
  on public.feedback for select
  using (account_id = auth.uid() or public.is_admin());

-- `with check` and not `using`: this is the rule for rows being written. The
-- account id cannot be forged, because it must equal the caller's own id.
drop policy if exists "feedback: insert own" on public.feedback;
create policy "feedback: insert own"
  on public.feedback for insert
  with check (account_id = auth.uid());

-- Only an admin marks a message handled. A student cannot edit what they sent,
-- which keeps the record of what was reported honest.
drop policy if exists "feedback: update admin" on public.feedback;
create policy "feedback: update admin"
  on public.feedback for update
  using (public.is_admin())
  with check (public.is_admin());

-- --------------------------------------------------- feedback screenshots --
-- A private bucket, read through short-lived signed links the API mints. Not
-- public: a screenshot of a bug is a screenshot of that student's own screen,
-- and an unguessable URL is not a permission.
--
-- Every object lives under the uploader's own id — 9f3c…/8b21….jpg — which is
-- what makes the policies below expressible: the first path segment is the
-- owner, so `storage.foldername(name)[1]` is who may touch it.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'feedback-shots',
  'feedback-shots',
  false,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "shots: insert own" on storage.objects;
create policy "shots: insert own"
  on storage.objects for insert
  with check (
    bucket_id = 'feedback-shots'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "shots: read own or admin" on storage.objects;
create policy "shots: read own or admin"
  on storage.objects for select
  using (
    bucket_id = 'feedback-shots'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
  );

-- An upload that was never attached to a message is the student's to remove;
-- one that was is part of the record, and the message cannot be edited either.
drop policy if exists "shots: delete own" on storage.objects;
create policy "shots: delete own"
  on storage.objects for delete
  using (
    bucket_id = 'feedback-shots'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ------------------------------------------------------- reset statistics --
-- Wipes every student's practice history: attempts, mock results and the
-- community's derived counters stay out of it — this is progress data only.
--
-- A definer function rather than a delete policy, for the same reason set_role()
-- is one. There is no delete policy on attempts or mocks anywhere in this file,
-- and that is deliberate: an append-only log cannot lose a row to a bug. This is
-- the single, named exception, and it checks the caller is the owner before it
-- touches anything.
--
-- Accounts are not touched. Signups are the one figure that must survive a
-- reset, because it is the only record of who ever joined.

create or replace function public.reset_statistics()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  removed_attempts bigint;
  removed_mocks bigint;
begin
  if not public.is_owner() then
    raise exception 'Only the owner can reset statistics' using errcode = '42501';
  end if;

  select count(*) into removed_attempts from public.attempts;
  select count(*) into removed_mocks from public.mocks;

  delete from public.attempts;
  delete from public.mocks;

  return json_build_object('attempts', removed_attempts, 'mocks', removed_mocks);
end;
$$;

revoke all on function public.reset_statistics() from public;
grant execute on function public.reset_statistics() to authenticated;

-- ==================================================== service sections ==
-- Lets the owner close part of the product while it is being worked on, so a
-- broken section shows a written explanation instead of a broken screen.
--
-- One row per section, created on demand — a missing row means open, so a
-- section nobody has ever touched needs no row and a new section added to the
-- app is open by default rather than invisible.

create table if not exists public.service_sections (
  -- The section's route key: community, practice, mock, review, progress.
  key        text primary key,
  closed     boolean not null default false,
  -- Shown to students in place of the section. Optional: there is a sensible
  -- default in the UI, and an owner closing something in a hurry should not
  -- have to write copy first.
  message    text,
  updated_by uuid references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.service_sections enable row level security;

-- Everyone signed in reads it: the app has to know what is closed in order to
-- say so, and that is not privileged information.
drop policy if exists "sections: read signed in" on public.service_sections;
create policy "sections: read signed in"
  on public.service_sections for select to authenticated using (true);

-- Writing is the owner's alone. Not is_admin(): closing the product for every
-- student is a different kind of decision from writing a question, and the
-- people who do the latter should not be able to do the former by accident.
drop policy if exists "sections: write owner" on public.service_sections;
create policy "sections: write owner"
  on public.service_sections for all
  using (public.is_owner())
  with check (public.is_owner());

-- ------------------------------------------------- question id integrity --
-- A blank id caused real data loss, so the database refuses one now rather than
-- trusting every client to.
--
-- What happened: the editor sends an empty id for a new question, an early
-- version of the API looked that empty value up among existing rows, and from
-- then on every save matched the blank row, was treated as an edit, and
-- overwrote it. Two admins writing to different sections ended up with one
-- question between them.
--
-- The delete runs first, because the constraint cannot be added while a row
-- violates it. It removes at most the single blank row; on a clean table it
-- matches nothing, which keeps this file re-runnable.

delete from public.custom_questions where trim(coalesce(id, '')) = '';

alter table public.custom_questions drop constraint if exists custom_questions_id_present;
alter table public.custom_questions
  add constraint custom_questions_id_present check (length(trim(id)) > 0);

-- ------------------------------------------------------- question figures --
-- Diagrams, graphs and tables belonging to questions.
--
-- Public, unlike feedback-shots. A figure is part of a question every signed-in
-- student loads, and a signed URL per figure would mean a round trip per image
-- plus an expiry that could strand a figure mid-test. Nothing private goes in
-- here: if it is in a question, every student is meant to see it.
--
-- Writing is admin-only, and the path convention is <uploader id>/<uuid>, the
-- same shape the feedback bucket uses, so the policies can key on the folder.

insert into storage.buckets (id, name, public)
values ('question-figures', 'question-figures', true)
on conflict (id) do update set public = true;

drop policy if exists "figures: read" on storage.objects;
create policy "figures: read"
  on storage.objects for select
  using (bucket_id = 'question-figures');

drop policy if exists "figures: admin writes own folder" on storage.objects;
create policy "figures: admin writes own folder"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'question-figures'
    and public.is_admin()
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Replacing a figure means uploading a new one, so update is only needed for the
-- overwrite case; delete lets an admin tidy up a figure they attached by mistake.
drop policy if exists "figures: admin manages own folder" on storage.objects;
create policy "figures: admin manages own folder"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'question-figures'
    and public.is_admin()
    and (storage.foldername(name))[1] = auth.uid()::text
  );


-- ---------------------------------------------------------------- avatars --
--
-- A profile picture, and the bucket it lives in.
--
-- The column is nullable-by-default-empty rather than null, matching every
-- other text column on profiles, so "no picture" is one value ('') instead of
-- two ('' and null) that every reader would have to handle separately.
--
-- The application is written to run against a database that has *not* had this
-- applied: the profile route selects the whole row and treats a missing
-- avatar_url as empty, so an un-migrated project keeps working with the picture
-- feature simply inert. Applying this turns it on; nothing else has to change.

alter table public.profiles
  add column if not exists avatar_url text not null default '';

-- ------------------------------------------------------------------ bucket --
--
-- Public, for the same reason question figures are: an avatar is shown beside
-- every post in a feed, and a signed URL per face would mean a round trip per
-- row and an expiry that can blank a timeline mid-scroll. Nothing private is
-- inferable from the file itself — the student chose it to be seen.

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "avatars: read" on storage.objects;
create policy "avatars: read"
  on storage.objects for select
  using (bucket_id = 'avatars');

-- Own folder only. Unlike figures this is not admin-gated — every student may
-- have a picture — so the folder check is the whole of the authorisation and
-- has to be exact: it is what stops one account writing into another's.
drop policy if exists "avatars: write own folder" on storage.objects;
create policy "avatars: write own folder"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "avatars: update own folder" on storage.objects;
create policy "avatars: update own folder"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Changing a picture leaves the old file behind, so delete is what lets a
-- student actually remove a photo rather than only stop pointing at it.
drop policy if exists "avatars: delete own folder" on storage.objects;
create policy "avatars: delete own folder"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
