/** Dashboard, mock-test setup and exam-countdown copy. */

import type { CopyDict } from "./index";

export const PLAN_COPY: CopyDict = {
  /* ---------------- dashboard ---------------- */
  "plan.overview": { en: "Your progress" },
  "plan.answered": { en: "Answered" },
  "plan.accuracy": { en: "Accuracy" },
  "plan.queue": { en: "In review" },
  "plan.ofBank": { en: "of the bank" },
  "plan.noAttempts": { en: "no attempts yet" },
  "plan.queueClear": { en: "all cleared" },
  "plan.startHere": { en: "Start with one session — ten questions, and this screen fills with your own data." },

  /* ---------------- exam countdown ---------------- */
  "plan.countdownLabel": { en: "Until the next SAT" },
  "plan.countdownDays": { en: "d" },
  "plan.countdownHours": { en: "h" },
  "plan.countdownMinutes": { en: "m" },
  "plan.countdownNone": { en: "No date announced yet" },
  "plan.countdownNoneHint": { en: "It shows up here as soon as College Board publishes the schedule." },

  /* ---------------- mock test setup ---------------- */
  "plan.mockTitle": { en: "SAT mock test" },
  "plan.mockSub": { en: "The official structure and timing. Modules run back to back; the timer submits for you." },
  "plan.mockTotal": { en: "Questions" },
  "plan.mockDuration": { en: "Duration" },
  "plan.mockScale": { en: "Score scale" },
  "plan.mockModules": { en: "Modules" },
  "plan.mockReady": { en: "The test is complete" },
  "plan.mockPartial": { en: "Some questions will be generated" },
  "plan.mockShortBody": { en: "The bank currently holds fewer questions than the full format needs. We can fill the gap with AI-written questions built to the same blueprint, with the same explanations. Without generation the test runs shortened, and each module's clock shortens with it." },
  "plan.mockGenerate": { en: "Fill in the questions" },
  "plan.mockGenerating": { en: "Generating…" },
  "plan.mockShortenedOk": { en: "Take the shortened test" },
  "plan.mockGenerated": { en: "Questions added to the bank" },
  "plan.mockGenPartial": { en: "Not every question could be added — the test still runs." },
  "plan.mockGenUnavailable": { en: "Generation is unavailable: the server has no access key configured. The shortened test still runs." },
  "plan.mockGenFailed": { en: "Could not generate the questions. Try again, or take the shortened test." },
  /* Shown on a generated item inside a test. A student sitting a practice exam
     is entitled to know which questions were not written by a human. */
  "plan.aiBadge": { en: "AI" },
  "plan.aiBadgeTitle": { en: "Question generated by AI against the SAT blueprint" },
  "plan.aiInBank": { en: "AI-generated" }
};
