import type { CopyDict } from "./index";

export const UNIVERSITY_COPY: CopyDict = {
  "universities.title": { en: "Browse Universities" },
  "universities.sub": { en: "Find universities that fit your SAT score and preferences." },
  "universities.search": { en: "Search universities" },
  "universities.searchPlaceholder": { en: "Name, city, state or country" },
  "universities.country": { en: "Country" },
  "universities.allCountries": { en: "All countries" },
  "universities.score": { en: "Your SAT score" },
  "universities.scorePlaceholder": { en: "e.g. 1450" },
  "universities.policy": { en: "Test policy" },
  "universities.allPolicies": { en: "All policies" },
  "universities.rangeFilter": { en: "SAT information" },
  "universities.allRanges": { en: "All universities" },
  "universities.publishedRanges": { en: "Published ranges only" },
  "universities.scoreFits": { en: "My score is in or above range" },
  "universities.result": { en: "university" },
  "universities.results": { en: "universities" },
  "universities.clear": { en: "Clear filters" },
  "universities.empty": { en: "No universities match these filters." },
  "universities.emptyBody": { en: "Try a broader location, policy or SAT filter." },
  "universities.satRange": { en: "SAT range" },
  "universities.notPublished": { en: "Not published" },
  "universities.view": { en: "View university" },
  "universities.source": { en: "Admissions source" },
  "universities.reach": { en: "Reach range" },
  "universities.inRange": { en: "In published range" },
  "universities.aboveRange": { en: "Above published range" },
  "universities.matchNote": { en: "Score context only — never an admission prediction." },
  "universities.dataNote": { en: "A focused starter directory. SAT ranges and policies link to official university sources and can change by application cycle." },
};
