/**
 * Pixel-art card art for the two SAT sections.
 *
 * Drawn rather than shipped as PNGs: sprites this small are a few dozen
 * rectangles, so they cost less than an image request, stay crisp at any card
 * size or pixel ratio, and can take their palette from the card they sit on.
 *
 * Both sprites are generated by scanline instead of hand-authored pixel maps.
 * A stepped diagonal — the thing that makes pixel art read as pixel art — falls
 * out of a scanline for free, and an isometric book or a tapering set square is
 * all diagonals. `outlineRuns` then walks the same scanlines to lay a one-pixel
 * black keyline around each shape, which is what holds the sprite together
 * against a saturated gradient.
 */

/** One horizontal run of pixels: y, inclusive x range, colour. */
type Run = { y: number; x0: number; x1: number; fill: string };

const OUTLINE = "#171418";

function rects(runs: Run[], keyPrefix: string) {
  return runs.map((run, i) => (
    <rect
      key={`${keyPrefix}-${i}`}
      x={run.x0}
      y={run.y}
      width={run.x1 - run.x0 + 1}
      height={1}
      fill={run.fill}
    />
  ));
}

/**
 * A one-pixel keyline around a set of runs.
 *
 * Left and right get a pixel each; top and bottom are covered by testing
 * whether the run above or below actually spans this column, which is what makes
 * a stepped edge come out cleanly rather than as a dotted line.
 */
function outlineRuns(runs: Run[]): Run[] {
  const byRow = new Map<number, Run[]>();
  for (const run of runs) {
    const row = byRow.get(run.y) ?? [];
    row.push(run);
    byRow.set(run.y, row);
  }

  const covered = (y: number, x: number) =>
    (byRow.get(y) ?? []).some((run) => x >= run.x0 && x <= run.x1);

  const out: Run[] = [];
  for (const run of runs) {
    out.push({ y: run.y, x0: run.x0 - 1, x1: run.x0 - 1, fill: OUTLINE });
    out.push({ y: run.y, x0: run.x1 + 1, x1: run.x1 + 1, fill: OUTLINE });
    for (const y of [run.y - 1, run.y + 1]) {
      for (let x = run.x0 - 1; x <= run.x1 + 1; x++) {
        if (!covered(y, x)) out.push({ y, x0: x, x1: x, fill: OUTLINE });
      }
    }
  }
  return out;
}

/* ================= Reading & Writing: a stack of books ================= */

type Book = {
  /** Bottom-left of the book's front face. */
  x: number;
  y: number;
  width: number;
  /** Rows of top face visible, i.e. how far the book leans away. */
  depth: number;
  /** Rows of page block below the top face. */
  pages: number;
  cover: string;
  coverShade: string;
  spine: string;
};

const PAGE = "#f7f4ec";
const PAGE_SHADE = "#cfc9bd";

/**
 * One book: an isometric top face, a block of page edges under it, and a strip
 * of cover below that. The top face steps one pixel right per row, which is the
 * whole isometric illusion.
 */
function bookRuns(book: Book): Run[] {
  const runs: Run[] = [];

  for (let j = 0; j < book.depth; j++) {
    const y = book.y + j;
    const x0 = book.x + (book.depth - 1 - j);
    const x1 = x0 + book.width;
    // The far row reads as the raised back edge, so it takes the shade.
    runs.push({ y, x0, x1, fill: j === 0 ? book.coverShade : book.cover });
  }

  for (let j = 0; j < book.pages; j++) {
    const y = book.y + book.depth + j;
    // Page edges sit slightly inside the cover, which is what makes the cover
    // read as overhanging them.
    runs.push({
      y,
      x0: book.x + 1,
      x1: book.x + book.width - 1,
      fill: j === book.pages - 1 ? PAGE_SHADE : PAGE,
    });
  }

  runs.push({
    y: book.y + book.depth + book.pages,
    x0: book.x,
    x1: book.x + book.width,
    fill: book.spine,
  });

  return runs;
}

const BOOKS: Book[] = [
  // Bottom of the pile first, so each book overlaps the one beneath it.
  {
    x: 1,
    y: 20,
    width: 26,
    depth: 3,
    pages: 3,
    cover: "#a855c7",
    coverShade: "#7e3aa0",
    spine: "#6b2f89",
  },
  {
    x: 3,
    y: 13,
    width: 25,
    depth: 3,
    pages: 3,
    cover: "#d9a06a",
    coverShade: "#b07c4a",
    spine: "#96663a",
  },
  {
    x: 5,
    y: 6,
    width: 24,
    depth: 4,
    pages: 3,
    cover: "#f2622f",
    coverShade: "#cc4a1d",
    spine: "#a83a15",
  },
];

function BooksSprite() {
  const body = BOOKS.flatMap(bookRuns);
  const top = BOOKS[BOOKS.length - 1];

  // A label patch and three ruled lines on the top cover: the detail that says
  // "book" rather than "coloured slab".
  const marks: Run[] = [
    { y: top.y + 1, x0: top.x + 17, x1: top.x + 21, fill: PAGE },
    { y: top.y + 2, x0: top.x + 16, x1: top.x + 20, fill: PAGE },
    ...[0, 1, 2].map((i) => ({
      y: top.y + 2,
      x0: top.x + 6 + i * 3,
      x1: top.x + 6 + i * 3,
      fill: top.coverShade,
    })),
    ...[0, 1, 2].map((i) => ({
      y: top.y + 3,
      x0: top.x + 5 + i * 3,
      x1: top.x + 5 + i * 3,
      fill: top.coverShade,
    })),
  ];

  return (
    <>
      {rects(outlineRuns(body), "bo")}
      {rects(body, "bb")}
      {rects(marks, "bm")}
    </>
  );
}

/* ================= Math: a set square ================= */

/**
 * A right triangle with a triangular window cut out of it, right angle at the
 * top left, hypotenuse falling to the bottom left — a set square lying on the
 * card. Tick marks run along the top edge, because a ruler without graduations
 * is just a wedge.
 */
function SetSquareSprite() {
  const top = 4;
  const bottom = 25;
  const left = 3;
  const right = 30;

  const body: Run[] = [];
  for (let y = top; y <= bottom; y++) {
    // How far along the fall we are; the right edge tapers to the left as it goes.
    const fall = (y - top) / (bottom - top);
    const x1 = Math.round(right - (right - left) * fall);
    if (x1 <= left) continue;
    body.push({ y, x0: left, x1, fill: "#f5c542" });
  }

  // The window: the same triangle inset, so the frame keeps an even thickness.
  const holeTop = top + 4;
  const holeBottom = bottom - 5;
  const holeLeft = left + 4;
  const holeRight = right - 8;
  const holeRuns: Run[] = [];
  const hole = new Set<string>();
  for (let y = holeTop; y <= holeBottom; y++) {
    const fall = (y - holeTop) / (holeBottom - holeTop);
    const x1 = Math.round(holeRight - (holeRight - holeLeft) * fall);
    if (x1 < holeLeft) continue;
    holeRuns.push({ y, x0: holeLeft, x1, fill: OUTLINE });
    for (let x = holeLeft; x <= x1; x++) hole.add(`${x},${y}`);
  }

  /** Split each body run around the window, so the hole is genuinely a hole. */
  const framed: Run[] = [];
  for (const run of body) {
    let start: number | null = null;
    for (let x = run.x0; x <= run.x1 + 1; x++) {
      const solid = x <= run.x1 && !hole.has(`${x},${run.y}`);
      if (solid && start === null) start = x;
      if (!solid && start !== null) {
        framed.push({ y: run.y, x0: start, x1: x - 1, fill: run.fill });
        start = null;
      }
    }
  }

  // Shading: the lower edge of each straight strip goes darker, which gives the
  // plastic a thickness rather than leaving it a flat yellow shape.
  const shade: Run[] = [
    { y: top + 3, x0: left, x1: right - 3, fill: "#d99b1f" },
    { y: bottom, x0: left, x1: left + 2, fill: "#d99b1f" },
    { y: top, x0: left, x1: right, fill: "#ffe08a" },
  ];

  // Graduations along the top edge: long marks every fourth, short between.
  const ticks: Run[] = [];
  for (let i = 0; i < 9; i++) {
    const x = left + 2 + i * 3;
    if (x > right - 2) break;
    const long = i % 2 === 0;
    for (let y = top + 1; y <= top + (long ? 2 : 1); y++) {
      ticks.push({ y, x0: x, x1: x, fill: OUTLINE });
    }
  }

  return (
    <>
      {rects(outlineRuns(body), "so")}
      {rects(framed, "sb")}
      {rects(shade, "ss")}
      {rects(ticks, "st")}
      {/* The window needs its own keyline, or the frame's inner edge reads as a
          smudge where the yellow simply stops. Outlining the window's row runs
          rather than its pixels keeps this to a couple of dozen rectangles; any
          keyline pixel that lands back inside the window is dropped. */}
      {rects(
        outlineRuns(holeRuns).filter((run) => !hole.has(`${run.x0},${run.y}`)),
        "sh",
      )}
    </>
  );
}

/* ================= the component ================= */

export function SubjectArt({
  kind,
  className = "",
}: {
  kind: "math" | "verbal";
  className?: string;
}) {
  return (
    <svg
      viewBox="0 0 34 30"
      className={`subject-art ${className}`}
      // Pixel art must not be smoothed; without this the browser bilinearly
      // resamples the SVG's rasterisation and the whole point is lost.
      shapeRendering="crispEdges"
      aria-hidden
    >
      {kind === "math" ? <SetSquareSprite /> : <BooksSprite />}
    </svg>
  );
}
